"""empty message

Revision ID: 2a82e41ef4ab
Revises: dde489761a67
Create Date: 2022-03-07 17:25:14.097797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a82e41ef4ab'
down_revision = 'dde489761a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('max_atmosphering_speed', sa.String(length=80), nullable=True))
    op.drop_column('vehicle', 'max_atmosfering_speed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('max_atmosfering_speed', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('vehicle', 'max_atmosphering_speed')
    # ### end Alembic commands ###
