"""empty message

Revision ID: 841e75a04953
Revises: 669e78db4305
Create Date: 2022-03-07 17:20:16.203935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '841e75a04953'
down_revision = '669e78db4305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet', 'created')
    op.add_column('vehicle', sa.Column('manufacturer', sa.String(length=80), nullable=True))
    op.drop_column('vehicle', 'created')
    op.drop_column('vehicle', 'manufaturer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('manufaturer', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('vehicle', sa.Column('created', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('vehicle', 'manufacturer')
    op.add_column('planet', sa.Column('created', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
