"""empty message

Revision ID: d1000c46ea9d
Revises: daa7c662f60e
Create Date: 2022-03-07 17:29:55.906523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1000c46ea9d'
down_revision = 'daa7c662f60e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('pilots', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle', 'pilots')
    # ### end Alembic commands ###
