"""empty message

Revision ID: daa7c662f60e
Revises: 2a82e41ef4ab
Create Date: 2022-03-07 17:28:48.420060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daa7c662f60e'
down_revision = '2a82e41ef4ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('films', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle', 'films')
    # ### end Alembic commands ###
