"""empty message

Revision ID: dde489761a67
Revises: 841e75a04953
Create Date: 2022-03-07 17:23:46.401381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dde489761a67'
down_revision = '841e75a04953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('length', sa.String(length=80), nullable=True))
    op.drop_column('vehicle', 'lenght')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('lenght', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('vehicle', 'length')
    # ### end Alembic commands ###
